### ISSUE TITLE
Npm won't launch

### ISSUE THREAD

**Issue by Caradepato** [nancialaudino/BloodBus#1]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bloodbus@0.0.0~prestart: bloodbus@0.0.0
6 info lifecycle bloodbus@0.0.0~start: bloodbus@0.0.0
7 verbose lifecycle bloodbus@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle bloodbus@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Tomas/bloodBus/BloodBus/app/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
9 verbose lifecycle bloodbus@0.0.0~start: CWD: /Users/Tomas/bloodBus/BloodBus/app
10 silly lifecycle bloodbus@0.0.0~start: Args: [ '-c', 'node ./bin/www' ]
11 silly lifecycle bloodbus@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle bloodbus@0.0.0~start: Failed to exec start script
13 verbose stack Error: bloodbus@0.0.0 start: `node ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid bloodbus@0.0.0
15 verbose cwd /Users/Tomas/bloodBus/BloodBus/app
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error bloodbus@0.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the bloodbus@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Caradepato** [comment]
This has been fixed -> the issue had to do with syntax, document was replaced with an older version and it worked. Exact point of error unknown but issue resolved.
